# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_nuts_fit <- function(q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, re_group, n_re_groups, model_type, sigma_beta = 10.0, sigma_re_scale = 2.5, phi_prior_shape = 1.0, phi_prior_rate = 0.01, n_iter = 2000L, n_warmup = 1000L, max_treedepth = 10L, adapt = TRUE, verbose = TRUE, seed = 0L) {
    .Call(`_quotr_cpp_nuts_fit`, q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, re_group, n_re_groups, model_type, sigma_beta, sigma_re_scale, phi_prior_shape, phi_prior_rate, n_iter, n_warmup, max_treedepth, adapt, verbose, seed)
}

cpp_hmc_basic <- function(q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, re_group, n_re_groups, model_type, sigma_beta = 10.0, sigma_re_scale = 2.5, phi_prior_shape = 1.0, phi_prior_rate = 0.01, n_iter = 2000L, n_warmup = 1000L, epsilon = 0.1, L = 10L, adapt = TRUE, verbose = TRUE, seed = 0L) {
    .Call(`_quotr_cpp_hmc_basic`, q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, re_group, n_re_groups, model_type, sigma_beta, sigma_re_scale, phi_prior_shape, phi_prior_rate, n_iter, n_warmup, epsilon, L, adapt, verbose, seed)
}

cpp_hmc_fit <- function(q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, re_group, n_re_groups, model_type_str, spatial_type_str, spatial_group, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, bym2_scale_factor, temporal_type_str, temporal_time_idx, temporal_group_idx, n_times, n_temporal_groups, n_temporal_params, temporal_cyclic, temporal_shared, tau_temporal_shape, tau_temporal_rate, sigma_beta, sigma_re_scale, phi_prior_shape, phi_prior_rate, tau_spatial_shape, tau_spatial_rate, zi_type_str, X_zi, zi_prior_sd, n_iter, n_warmup, L, n_chains, seed, n_threads, verbose) {
    .Call(`_quotr_cpp_hmc_fit`, q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, re_group, n_re_groups, model_type_str, spatial_type_str, spatial_group, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, bym2_scale_factor, temporal_type_str, temporal_time_idx, temporal_group_idx, n_times, n_temporal_groups, n_temporal_params, temporal_cyclic, temporal_shared, tau_temporal_shape, tau_temporal_rate, sigma_beta, sigma_re_scale, phi_prior_shape, phi_prior_rate, tau_spatial_shape, tau_spatial_rate, zi_type_str, X_zi, zi_prior_sd, n_iter, n_warmup, L, n_chains, seed, n_threads, verbose)
}

cpp_get_max_threads <- function() {
    .Call(`_quotr_cpp_get_max_threads`)
}

cpp_hmc_simple <- function(q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, re_group, n_re_groups, model_type_str, sigma_beta = 10.0, sigma_re_scale = 2.5, phi_prior_shape = 2.0, phi_prior_rate = 0.1, n_iter = 2000L, n_warmup = 1000L, L = 20L, adapt = TRUE, verbose = TRUE, seed = 0L) {
    .Call(`_quotr_cpp_hmc_simple`, q_init, y_num, y_denom, y_denom_cont, X_num, X_denom, re_group, n_re_groups, model_type_str, sigma_beta, sigma_re_scale, phi_prior_shape, phi_prior_rate, n_iter, n_warmup, L, adapt, verbose, seed)
}

cpp_laplace_fit <- function(y, n, X, re_idx, n_re_groups, sigma_re, family, phi = 1.0, max_iter = 100L, tol = 1e-6, n_threads = 1L) {
    .Call(`_quotr_cpp_laplace_fit`, y, n, X, re_idx, n_re_groups, sigma_re, family, phi, max_iter, tol, n_threads)
}

cpp_laplace_get_max_threads <- function() {
    .Call(`_quotr_cpp_laplace_get_max_threads`)
}

cpp_laplace_fit_spatial <- function(y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, tau_spatial, family, phi = 1.0, max_iter = 100L, tol = 1e-6, n_threads = 1L) {
    .Call(`_quotr_cpp_laplace_fit_spatial`, y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, tau_spatial, family, phi, max_iter, tol, n_threads)
}

cpp_laplace_sample <- function(mode, H, n_samples) {
    .Call(`_quotr_cpp_laplace_sample`, mode, H, n_samples)
}

cpp_laplace_fit_bym2 <- function(y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, sigma_spatial, rho, scale_factor, family, phi = 1.0, max_iter = 100L, tol = 1e-6, n_threads = 1L) {
    .Call(`_quotr_cpp_laplace_fit_bym2`, y, n, X, re_idx, n_re_groups, sigma_re, spatial_idx, n_spatial_units, adj_row_ptr, adj_col_idx, n_neighbors, sigma_spatial, rho, scale_factor, family, phi, max_iter, tol, n_threads)
}

cpp_pg_binomial_gibbs <- function(y, n, X, group, n_groups, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_scale = 2.5, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_quotr_cpp_pg_binomial_gibbs`, y, n, X, group, n_groups, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_scale, store_eta, verbose, n_threads)
}

cpp_pg_get_max_threads <- function() {
    .Call(`_quotr_cpp_pg_get_max_threads`)
}

cpp_pg_binomial_gibbs_spatial <- function(y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_tau_shape = 1.0, prior_tau_rate = 0.01, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_quotr_cpp_pg_binomial_gibbs_spatial`, y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_tau_shape, prior_tau_rate, store_eta, verbose, n_threads)
}

cpp_pg_binomial_gibbs_bym2 <- function(y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, scale_factor, n_iter = 2000L, n_warmup = 1000L, thin = 1L, prior_beta_sd = 10.0, prior_sigma_re_scale = 2.5, prior_sigma_spatial_scale = 2.5, prior_rho_alpha = 0.5, prior_rho_beta = 0.5, store_eta = FALSE, verbose = TRUE, n_threads = 1L) {
    .Call(`_quotr_cpp_pg_binomial_gibbs_bym2`, y, n, X, re_group, n_re_groups, spatial_group, n_spatial_units, adj_list, n_neighbors, scale_factor, n_iter, n_warmup, thin, prior_beta_sd, prior_sigma_re_scale, prior_sigma_spatial_scale, prior_rho_alpha, prior_rho_beta, store_eta, verbose, n_threads)
}

cpp_rpg1 <- function(z) {
    .Call(`_quotr_cpp_rpg1`, z)
}

cpp_rpg <- function(b, z) {
    .Call(`_quotr_cpp_rpg`, b, z)
}

